# Generated by Django 3.1.7 on 2021-02-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestorage',
            name='upload_file',
            field=models.ImageField(upload_to=''),
        ),
    ]
